### ISSUE TITLE
Add the `la_function` and `la_service` metadata fields

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#10]
Add the following 2 metadata fields
La_function
La_ service
They are as per Appendix B (datasets extra fields) http://data.gov.uk/sites/default/files/library/Harvesting%20guide.pdf

**Comment by amercader** [comment]
This turned out to be a little more complex than expected. There are 113 and ~1600 possible values for functions and services, and you can have more than one value on each field. Also these are generic fields that all local authority CKAN instances need to provide if they need to be harvested into DGU, so I created a separate extension to reuse all widgets, validators, etc:

https://github.com/okfn/ckanext-esdstandards

The end result looks like this:

![cljubfm](https://cloud.githubusercontent.com/assets/200230/6664322/86d4171a-cbc6-11e4-9fbe-e2a4dd957f14.png)

There are a couple of [issues](https://github.com/okfn/ckanext-esdstandards/issues) on that extension that are non blockers for Salford but would be good to get out of the way now that we are working on it.

On the ckanext-salford side there is some work to integrate it:
- [x] Modify the schema and the templates to add the fields
- [ ] They want to be able to facet by these fields, so we'll need to add a custom schema with them (as they multivalued)

**Comment by amercader** [comment]
This is ready for reviewing:

https://salforddataquay.uk/dataset/new
https://salforddataquay.uk/dataset/scc-public-toilets
https://salforddataquay.uk/dataset
